### ISSUE TITLE
Display Audio Gen1?

### ISSUE THREAD

**Issue by beneficadoramocaba** [greenluigi1/DAudio2GuiTemplate#3]
Did your explorations give you any insight into earlier vehicles (2016 up to 2021 for some models) with the Gen1 head units? Hyundai USA has released multiple updates for these vehicles, but they do not appear to install for vehicles from other countries...
https://update.hyundai.com/US/EN/updateNoticeView/983/pop2

**Comment by greenluigi1** [comment]
Unfortunately, I have not looked too much into the Gen 1 head units.

**Comment by beneficadoramocaba** [comment]
Ok, thanks. From what I gather, they run Android 4.2.2... I imagine some part of your hard work will be applicable to it, though I may never have the time to dig into it.

**Comment by piotr-cz** [comment]
@beneficadoramocaba 
Take a look here: https://github.com/rgerganov/gen5fw

**Comment by beneficadoramocaba** [comment]
> @beneficadoramocaba Take a look here: https://github.com/rgerganov/gen5fw

Thanks but that only appears to apply to Gen5 w/buttons for gps features.

**Comment by piotr-cz** [comment]
I think that the process is same for both navi and non-navi units.
The only missing part is to somehow get firmware for it.

If your car is intended for US region - process is described in this repo's author blog post series.

In other case - there is a chance that authorized Hyundai service center will have it.

See hyundai.com > [How to update your maps & infotainment software.](https://www.hyundai.com/eu/driving-hyundai/owning-a-hyundai/bluelink-connectivity/updates.html):

> **Let your local Hyundai dealer update your software.**
> Keep it simple. When you make your next Hyundai vehicle maintenance appointment, just ask your dealer to also update your vehicle with the latest maps and infotainment software. 

> **How often is there a new software update?**
> Usually new maps and software are updated twice a year.

However I had a vehicle maintenance last year and they didn't perform any software updates, but I didn't ask for it either.

Another option would be to inspect a diff of US region navi and non-navi firmwares (see <https://update.hyundai.com/US/EN/Main>) and prepare custom one, but it would be pretty complicated and risky.
