### ISSUE TITLE
Car audio 

### ISSUE THREAD

**Issue by sartusd** [greenluigi1/DAudio2GuiTemplate#4]
Hi, I want to improve the sound in the car, and I noticed an unpleasant feature, some of the bass is cut, and the rear speakers play at half power. I read your blog about firmware hacking, and maybe during your research you came across sound settings and how can I fix my problem?

**Comment by greenluigi1** [comment]
In the Engineering mode app there is code that can update the DSP from a bin file.
It looks like this is the list of the valid bin files:
- RADIO_EXT_2D.BIN
- SOUND_INT_2D.BIN
- SOUND_ARKA_INT_2D.BIN
- SOUND_EXT_2D.BIN
- ARKAMYS_HIFI_2D.BIN
- ARKAMYS_DSP_2D.BIN
- RADIO_INT_5D.BIN
- RADIO_EXT_5D.BIN
- SOUND_INT_5D.BIN
- SOUND_ARKA_INT_5D.BIN
- SOUND_EXT_5D.BIN
- ARKAMYS_HIFI_5D.BIN
- ARKAMYS_DSP_5D.BIN
- RADIO_INT_4D.BIN
- RADIO_EXT_4D.BIN
- SOUND_INT_4D.BIN
- SOUND_ARKA_INT_4D.BIN
- SOUND_EXT_4D.BIN
- ARKAMYS_HIFI_4D.BIN
- ARKAMYS_DSP_4D.BIN
- RADIO_INT_2D.BIN

Unfortunately, I do not know where you can find these bin files, their structure, or how you could edit them if you found one.
